# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EstateApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EstateApp

  pod 'SlideMenuControllerSwift'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'WARangeSlider'
  pod 'GooglePlaces'
  pod 'GooglePlacePicker'
  pod 'GoogleMaps'
  pod 'IQKeyboardManagerSwift', '5.0.3'
  pod 'R.swift'
  
end
